---
  - name: Create and delete the bulk host creation
    hosts: AAP
    gather_facts: no
    collections:
       - awx.awx

    pre_tasks:
    - name: Checking the Controller Host/Groups/Inventory variable values
      ansible.builtin.assert:
          that:
            - controller_host_device_name|default('', true) != ''
            - controller_groups_name|default('', true) != '' 
            - controller_inventory_name|default('', true) != ''
          fail_msg: "controller_host_device_name ,controller_groups_name,controller_inventory_name should not be empty"
          success_msg: " Variable 'controller_host_device_name','controller_groups_name' & controller_inventory_name passed value validation!"

    - name: Create the bulk host list as per standard dictonary value
      ansible.builtin.set_fact: 
          controller_host_list: '{{ controller_host_list|default([]) + [{"name":item,"enabled":true}] }}'
      loop: "{{ controller_host_device_name.split(',') }}"

    tasks:
    - name: Include the Bulk host creation role
      ansible.builtin.include_role:
          name: bulk-host-creation
      vars:
        host_value: "{{ controller_host_list }}"    

    - name: Include the Bulk host creation role
      ansible.builtin.include_role:
          name: group-creation