---
# defaults file for acl_configuration
__extended_acl_rule: []
__standard_acl_rule: []
change_number: "CHG000001"
_email_body_message: |
            <font face="Arial"> 
            Hi "{{tower_user_name}}"
            Kindly find the attached ACL_report.
            Ansible_Job_template: "{{tower_job_template_name}}"
            Ansible_Job_id: "{{tower_job_id}}"
            Ansible_job_launched_by: "{{tower_user_id}}"
_email_address_to: []
_email_address_cc: []

report_generation_value: |
      ==============================
      ACL_POST_CHECK_DATA
      ==============================
      {% for host in ansible_play_hosts_all %}
      {% if 'ping_status' in hostvars[host] and not hostvars[host]['ping_status']['failed'] %}
      ----------------------------
      Hostname: "{{host}}"
      ----------------------------
      Before_ACL_Config
      ----------------------------
      ACL_name: "{{acl_name}}"
      ACL_Type: "{{ hostvars[host]['acl_type'] }}"
      ===========================================
      {% set rule_lines_ = hostvars[host]['_before_show_acl_desired_value']['stdout_lines'][1:] %}
      {% for i in _rule_lines %}
      ACL_Entry: 
      "{{ rule_lines_ }}"
      {% endfor %}
      ============================================
    
      ---------------------------
      After_New_ACL_Config_Pushed
      ---------------------------
      ACL_name: "{{acl_name}}"
      ACL_Type: "{{ hostvars[host]['acl_type'] }}"
      ===========================================

      {% set rule_lines_after = hostvars[host]['_before_show_acl_desired_value']['stdout_lines'][1:] %}
      {% for i in rule_lines_after %}
      ACL_Entry: 
      "{{ rule_lines_ }}"
      {% endfor %}
  
      ============================================
      {% else %}
      ----------------------------
      Hostname: "{{host}}"
      ----------------------------
      This Switch not reachable or have some issue during the ansible execution kindly check manually
      {% endif %}
      {% endfor %}

